name: Angular GitHub CI
on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint
      
      - name: Build
        run: npm run build:prod

      - name: Run Tests
        run: npm run test 
